name: react
description: React JS bindings for Dart.
version: 0.0.1
author: Dan Schultz <schultz.t.dan@gmail.com>
homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  js: ^0.6.0-beta
dev_dependencies:
  browser: any
